apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-stable
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
