apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/kdubois/quinoa-wind-turbine-rollouts
      revision: main
      directories:
      - path: rollouts/workloads/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
      project: workloads
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/kdubois/quinoa-wind-turbine-rollouts
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
